### PR TITLE
feat: support tagging recordings

### PR DESCRIPTION
**Pull request by honicole**
Hello,

I am submitting a PR to support a wrapper for [tagging Hotjar recordings](https://help.hotjar.com/hc/en-us/articles/115011819488-How-to-Tag-your-Hotjar-Recordings#auto) so my team can use this in a project.
```
hj('tagRecording', ['tag1', 'tag2']);
```

I am unfamiliar with contributing to open-source projects so please let me know if I am missing anything.
Thanks!

### CODE REVIEW

**Comment by olavoparno** [comment]
@honicole thank you very much for your contribution, it really gladens me knowing this tool is of help. Thanks for the grammar fixes too haha

@all-contributors please add @honicole for code, ideas, doc

**Comment by olavoparno** [comment]
I'll reply here once the new version is up and running. We still have to add it to actions.

**Comment by olavoparno** [comment]
Please do check for version 1.2.0 and report back if everything is ok @honicole 

Again, thank you.

https://www.npmjs.com/package/react-use-hotjar/v/1.2.0

**Comment by honicole** [comment]
@olavoparno Hi, it is working great, thanks!

**Pull request merged**
